### ISSUE TITLE
Doesn't handle blank arguments (i.e., '')

### ISSUE THREAD

**Issue by petonic** [Firedrake/dymo-labelmanager#1]
Hi -- I've noticed that blank arguments make txt2img blow-up.  I've crufted together a hack to handle them, and the same hack also makes it so that you can use multiple blank arguments to make the font smaller, while still keeping the lines centered.  

Are you open to looking at the code?

**Comment by Firedrake** [comment]
I am. Thanks again for your patch, but I took a slightly different approach. If it doesn't meet your requirements, do give me a shout.
